name = "Delightful Creations"
author = "FrozenOrchestra"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c0be84afe41e003155aa9afe8aef3c4c17f0c94ffd0a96a53295b003889d5eb"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
