name = "Delightful Creations"
author = "FrozenOrchestra"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a72aeddd388fe8c6c06490f2b75e6547c114c935e2b0a44ac4e3a797cf420a9"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
